version: '2.4'
services:
  envoy:
    image: envoyproxy/envoy:v1.21-latest
    ports:
      - "8080:8080"
      - "8081:8081" # Port to access Envoy's admin interface
      - "8800:8800" # Port to access the api through Envoy

    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
  # api:
  #   image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
  #   command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "4000"]
  #   ports:
  #     - "4000:4000"
  #   volumes:
  #     - ./api.py:/app/api.py



  server1:
    container_name: server1
    build: ./server1
    image: server1
    ports:
      - '4000:4000'
    volumes:
      - server1-volume:/usr/src/server1
      - server1-node_modules:/usr/src/server1/node_modules

    networks:
      - envoy-network

  server2:
    container_name: server2
    build: ./server2
    image: server2
    ports:
      - '4001:4001'
    networks:
      - envoy-network

volumes:
  server1-volume: null
  server1-node_modules: null
networks:
  envoy-network:
    driver: bridge
